trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

# =============================
# BUILD
# =============================
- stage: Build
  displayName: Build Application

  jobs:
  - job: BuildJob

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '9.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop



# =============================
# PRODUCTION DEPLOYMENT
# =============================
- stage: DeployProduction

  displayName: Deploy Production

  dependsOn: Build

  jobs:

  - deployment: ProdDeploy

    environment: Production

    strategy:
      runOnce:
        deploy:

          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1

            inputs:

              azureSubscription: 'myservice-connection'
              appType: 'webApp'

              appName: 'aecsazuredevopslogicapp'
              resourceGroupName: 'WP_SL_User_087'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'
# =============================
# API FUNCTIONAL TEST
# =============================
- stage: APIFunctionalTest

  displayName: API Functional Testing

  dependsOn: DeployProduction

  jobs:

  - job: ValidateAPI

    steps:

    - task: PowerShell@2
      displayName: 'Validate Customers API'

      inputs:
        targetType: 'inline'

        script: |

          $baseUrl = "https://aecsazuredevopslogicapp.azurewebsites.net"

          Write-Host "Testing GET Customers"

          $response = Invoke-WebRequest `
            -Uri "$baseUrl/api/customers" `
            -Method Get

          if($response.StatusCode -ne 200)
          {
            throw "GET Customers Failed"
          }

          Write-Host "GET Customers Passed"