name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: aecsacrdevopsdemo.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Image
      run: |
        docker build \
        -t githubdemo:${{ github.run_number }} \
        -f DemoLogicAppApi/Dockerfile \
        DemoLogicAppApi

    - name: Tag Image
      run: |
        docker tag githubdemo:${{ github.run_number }} \
        aecsacrdevopsdemo.azurecr.io/githubdemo:${{ github.run_number }}

    - name: Push Image
      run: |
        docker push \
        aecsacrdevopsdemo.azurecr.io/githubdemo:${{ github.run_number }}